卒業試験　テーブル設計
yuri315/tenki_hairset pull request #3
Opened 2022-11-13 10:20 UTC by yuri315

# 卒業試験
テーブル設計作成しましたので、ご確認をお願いいたします
参考資料をもとに考えましたが、イメージがわきづらかったです。あまりに違うようでしたら、一度技術面談で、相談しようと思います。
よろしくお願いたします。
# テーブル設計
https://gyazo.com/15934f8033d6003ccdd0cccf3d35f62f

2022-11-13 22:51 UTC, busitora requested changes
こちらはポートフォリオのER図依頼で間違いないですかね?

- timestamp は書くか否か統一してください
- hair_types.hair_type になるので テーブルとカラムの命名の重複は避けましょう
- when_weather は命名が良くないのでかえましょう。
- my_tenkis はテーブルの命名が良くないのでかえましょう。

一旦こちらの対応お願いします。

2022-11-15 05:47 UTC, yuri315 commented
ご返信ありがとうございます。
ポートフォリオのER図で間違いないです。
- timestamp なしに統一しました。
-  hair_typeのカラム名をtypeに変更しました。
- when_weatherはtoday_or_tomorrow_weatherに変更しました。
- my_tenkisはmy_weathersに変更しました。

ER図
https://gyazo.com/d6d213725e5e98cacf4f642fb465d39b
です。

よろしくお願いいたします。

2022-11-15 23:04 UTC, yuri315 commented
- 各カラムに型情報を入力しました。
- typeのカラム名変更しました。（hairに変更）
- 各テーブルの説明
  - usersにはusermの基本情報。名前、e-mailアドレス、パスワード、管理者か、一般ユーザーか。
  - hair_typesには、髪質がハードかソフトか。
  - weatherforecastsにはAPIでとってきたデータ。
     風速、天気、湿度、気温、日付、取得日。
  - my_weathersには会員の登録情報。会員ユーザーが、地域、髪質、今日の天気か明日の天気どちらを表示するか、を選択し、登録できる。
  - resultsには、非会員の髪型アドバイス診断結果。weather_forecastsで取得した結果をもとに、今日、または明日の天気と髪型アドバイス。
  - user_resultsには会員の髪型アドバイス診断結果。会員ユーザーが登録情報と天気予報APIの情報をもとに、アドバイスを受けることができる。
  - citiesにはAPIで天気予報を取得する地域を入れる。

という感じです。
- 天気APIを使っている方の情報を見て、weatherforecastとcityのカラムを追加しました。
- また、会員と非会員の診断結果を別にしたいので、resultのテーブルを分けました。

考えているうちにこんがらがってしまいました。
お手数をおかけしますが、よろしくお願いいたします。

ER図
https://gyazo.com/7d8286dbafa7638d28f2569f0cfac0f1

2022-11-15 23:12 UTC, yuri315 commented
- 各カラムに型情報を入力しました。
- typeのカラム名変更しました。（hairに変更）
- 各テーブルの説明
  - usersにはusermの基本情報。名前、e-mailアドレス、パスワード、管理者か、一般ユーザーか。
  - hair_typesには、髪質がハードかソフトか。
  - weatherforecastsにはAPIでとってきたデータ。
     風速、天気、湿度、気温、日付、取得日。
  - my_weathersには会員の登録情報。会員ユーザーが、地域、髪質、今日の天気か明日の天気どちらを表示するか、を選択し、登録できる。
  - resultsには、非会員の髪型アドバイス診断結果。weather_forecastsで取得した結果をもとに、今日、または明日の天気と髪型アドバイス。
  - user_resultsには会員の髪型アドバイス診断結果。会員ユーザーが登録情報と天気予報APIの情報をもとに、アドバイスを受けることができる。
  - citiesにはAPIで天気予報を取得する地域を入れる。

という感じです。
- 天気APIを使っている方の情報を見て、weatherforecastとcityのカラムを追加しました。
- また、会員と非会員の診断結果を別にしたいので、resultのテーブルを分けました。

考えているうちにこんがらがってしまいました。
お手数をおかけしますが、よろしくお願いいたします。

ER図
https://gyazo.com/7d8286dbafa7638d28f2569f0cfac0f1

2022-11-17 05:37 UTC, Tsuchiya2 commented
ER図はURLだけでなく、スクリーンショットの共有もお願いします。
以下気になった点の一部になります。

■ usersテーブル
・sorceryやdeviceといったgemは使わずにログイン周りを実装する予定でしょうか？（カラムから推測）

■ hair_typesテーブル
・テーブル名をhairsテーブルとして、カラム名をtypeにしても良いかと感じました。（user.hair.typeで呼び出すイメージから）
・user_idをinteger型にしていますが、reference型を使う認識であっていますでしょうか？
・usersテーブルとの関係性がER図からは重なっていてよく分からなかったです。

■ weather_forecastsテーブル
・hair_typesテーブルとの関係性は...1対1..??であっていますか？（ER図からは読み取りにくかったため）

■ resultsテーブル
・「非会員の髪型アドバイス診断結果」と説明がありましたが、非会員のデータを保存しておく必要があるのか気になりました。
・today_or_tommorrow_weatherカラムも変更した方が良いかと感じました。例：17日時点で18日は明日ですが、時間が進むに連れて18日は今日→昨日→...となっていくので、命名とご自身が考えているものとに乖離が生まれそうです。

■ citiesテーブル
・geonames_id、これはどんな値を保存するカラムなのか、カラム名からは想像が難しかったです。（どんな値を保存する予定でしょうか？）

2022-11-17 08:31 UTC, yuri315 commented
コメントありがとうございます。
> ■ usersテーブル
> ・sorceryやdeviceといったgemは使わずにログイン周りを実装する予定でしょうか？（カラムから推測）

sorceryを使う予定です。訂正しました。

> ■ hair_typesテーブル
> ・テーブル名をhairsテーブルとして、カラム名をtypeにしても良いかと感じました。（user.hair.typeで呼び出すイメージから）
> ・user_idをinteger型にしていますが、reference型を使う認識であっていますでしょうか？
> ・usersテーブルとの関係性がER図からは重なっていてよく分からなかったです。

- カラム名をtypeに戻しました。
- integerではなく、referenceでした。reference型に変更しました。
- userテーブルと関連づけるのではなく、my_weatherと関連づけないといけないと思い変更しました。

> ■ weather_forecastsテーブル
> ・hair_typesテーブルとの関係性は...1対1..??であっていますか？（ER図からは読み取りにくかったため）

hair_typesテーブルと関連づけるより、my_weatherと関連づけないといけないと思い変更しました。

> ■ resultsテーブル
> ・「非会員の髪型アドバイス診断結果」と説明がありましたが、非会員のデータを保存しておく必要があるのか気になりました。

削除しました。

> ・today_or_tommorrow_weatherカラムも変更した方が良いかと感じました。例：17日時点で18日は明日ですが、時間が進むに連れて18日は今日→昨日→...となっていくので、命名とご自身が考えているものとに乖離が生まれそうです。

カラム名をdateに変更しました。

> ■ citiesテーブル
> ・geonames_id、これはどんな値を保存するカラムなのか、カラム名からは想像が難しかったです。（どんな値を保存する予> 定でしょうか？）

天気予報のAPIを使用する際に、CITY IDを取得するようなので、それを保存するカラムです。

関連が全体的に曖昧だったので、復習し直し、考え直しました。
確認をお願いいたします。
<img width="486" alt="スクリーンショット 2022-11-17 17 29 35" src="https://user-images.githubusercontent.com/101074621/202395649-d659ab7c-31db-451c-9548-b20227dfd993.png">

2022-11-17 08:31 UTC, yuri315 commented
コメントありがとうございます。
> ■ usersテーブル
> ・sorceryやdeviceといったgemは使わずにログイン周りを実装する予定でしょうか？（カラムから推測）

sorceryを使う予定です。訂正しました。

> ■ hair_typesテーブル
> ・テーブル名をhairsテーブルとして、カラム名をtypeにしても良いかと感じました。（user.hair.typeで呼び出すイメージから）
> ・user_idをinteger型にしていますが、reference型を使う認識であっていますでしょうか？
> ・usersテーブルとの関係性がER図からは重なっていてよく分からなかったです。

- カラム名をtypeに戻しました。
- integerではなく、referenceでした。reference型に変更しました。
- userテーブルと関連づけるのではなく、my_weatherと関連づけないといけないと思い変更しました。

> ■ weather_forecastsテーブル
> ・hair_typesテーブルとの関係性は...1対1..??であっていますか？（ER図からは読み取りにくかったため）

hair_typesテーブルと関連づけるより、my_weatherと関連づけないといけないと思い変更しました。

> ■ resultsテーブル
> ・「非会員の髪型アドバイス診断結果」と説明がありましたが、非会員のデータを保存しておく必要があるのか気になりました。

削除しました。

> ・today_or_tommorrow_weatherカラムも変更した方が良いかと感じました。例：17日時点で18日は明日ですが、時間が進むに連れて18日は今日→昨日→...となっていくので、命名とご自身が考えているものとに乖離が生まれそうです。

カラム名をdateに変更しました。

> ■ citiesテーブル
> ・geonames_id、これはどんな値を保存するカラムなのか、カラム名からは想像が難しかったです。（どんな値を保存する予> 定でしょうか？）

天気予報のAPIを使用する際に、CITY IDを取得するようなので、それを保存するカラムです。

関連が全体的に曖昧だったので、復習し直し、考え直しました。
確認をお願いいたします。
<img width="486" alt="スクリーンショット 2022-11-17 17 29 35" src="https://user-images.githubusercontent.com/101074621/202395649-d659ab7c-31db-451c-9548-b20227dfd993.png">

2022-11-17 10:59 UTC, busitora commented
> カラム名をtypeに戻しました。
こちら、type 使う場合は  `self.inheritance_column` で変えれば使えるとは思いますが、任せます

アソシエーションの矢印足りていないのでしっかり全てのリレーションで書くようにしましょう！
weather_id については、 API取得の値を直で insert されるのですか？
それでもいいですがシンプルに weahters テーブルにAPIの値変換して もいいのかなと。
weather_forecasts に city_id は必要ですか? 用途が気になります

2022-11-17 14:42 UTC, yuri315 commented
> こちら、type 使う場合は self.inheritance_column で変えれば使えるとは思いますが、任せます

テーブル名をhairsにし、カラム名を、hair_typeにしました。

> アソシエーションの矢印足りていないのでしっかり全てのリレーションで書くようにしましょう！

my_weatherとuser_resultの矢印変更しました。

weather_id については、 API取得の値を直で insert されるのですか？
それでもいいですがシンプルに weahters テーブルにAPIの値変換して もいいのかなと。

直でと思っていましたが、シンプルにしたいので、変更します。新たにweatherテーブルを追加し、APIでとってきた値を、文字に変換し、保存したいと思います。新たにテーブルを作るということで、あってますでしょうか。

> weather_forecasts に city_id は必要ですか? 用途が気になります

確かに、my_weatherにあるので、いらないですね。消しました。

よろしくお願いいたします。

<img width="696" alt="スクリーンショット 2022-11-17 23 41 09" src="https://user-images.githubusercontent.com/101074621/202476151-de87229d-44b8-4988-9c05-11d1b4fb4b5f.png">

2022-11-17 23:42 UTC, takyyk commented
@yuri315 
my_whetherの内容は要はユーザーの登録情報ということですかね？
それではuserテーブルに格納できるかと思おうのですがどうでしょうか？

あとwhether_forcastテーブルに関してのacquire_atに関してですが、何が入ることを想定していますかね？
確認のため質問しました。

2022-11-18 00:49 UTC, yuri315 commented
ご返信ありがとうございます。

> my_whetherの内容は要はユーザーの登録情報ということですかね？
> それではuserテーブルに格納できるかと思おうのですがどうでしょうか？

ユーザーの登録情報です。
userテーブルに格納しました。
マイメニューのイメージでバラバラにしてしまいましたが、確かに一緒にした方がいいですね。

> あとwhether_forcastテーブルに関してのacquire_atに関してですが、何が入ることを想定していますかね？

データーの取得日を格納する予定です。


よろしくお願いいたします。
<img width="813" alt="スクリーンショット 2022-11-18 9 48 33" src="https://user-images.githubusercontent.com/101074621/202590995-b9007c13-e22f-4fc3-9cb2-e1934cc5a390.png">

2022-11-18 11:57 UTC, takyyk commented
@yuri315 
あと一つ確認です！
weathersテーブルとweathers_forecastsテーブルで1対多でテーブルを分けているのは何かAPI上の理由とかある形ですかね？

2022-11-18 13:41 UTC, yuri315 commented
> weather_id については、 API取得の値を直で insert されるのですか？
> それでもいいですがシンプルに weahters テーブルにAPIの値変換して もいいのかなと。

という意見をいただいて、テーブルを分けました。元々は、weather_forcastテーブルにweather_idを作って、天気idを入れて、と思っていました。戻した方が良いのでしょうか。

2022-11-19 02:26 UTC, murata0705 commented
やりたいことの内容の確認ですが、

> マイメニューには、一つの髪質、地域、日付を登録できる。

これはマイメニューに髪型、地域、日付を登録すると、そのタイミングでアドバイスが返ってくるということで良いですか？
例えば、今マイメニューに明日の日付で髪型、地域を登録すると、明日の天気に基づいたアドバイスが帰ってくるとことですかね？

で、たとえば2回目のアドバイスを受けたい場合はマイメニューを更新するとアドバイスを受けることができるという認識で良いですか？

アドバイスを受けたいタイミングでマイメニューを変更すると、アドバイスが表示され、user_results が増えるイメージ？

2022-11-19 12:07 UTC, yuri315 commented
ご返信ありがとうございます。
マイメニューを変更、登録したタイミングでも、アドバイスが表示されるし、マイメニューに登録してあれば、会員ページのトップ画面を開いた時に、最新の情報とアドバイスを受け取ることができ、user_results が増えるイメージです。

2022-11-19 12:10 UTC, murata0705 commented
その場合、マイメニューには髪型と地域のみ必要で、日付は不要ではないでしょうか？

2022-11-19 12:15 UTC, yuri315 commented
dateのところですが、日付を登録してほしいのではなく、利用するとき、明日の天気を見たいか、今日の天気を見たいかをマイメニューに設定してもらい、その結果を表示するというイメージです。
カラム名がいいものが思いつかず、dateとしてしまいました。

2022-11-19 12:21 UTC, murata0705 commented
そしたら、`forecast_day` とかにして、enum で、
```

2022-11-19 12:30 UTC, yuri315 commented
users
これはユーザー情報を保存
> user_results
> アドバイスの履歴
> cities, hair
> 予想に必要な情報
> という認識で良いですか？

その通りです。

wether_forecastsはAPIでとった情報を保存するテーブルです。
weathersは

> weather_id については、 API取得の値を直で insert されるのですか？
> それでもいいですがシンプルに weahters テーブルにAPIの値変換して もいいのかなと。

とアドバイスをいただいて、 weahters テーブルにAPIの値変換するテーブルを作成しました。

先ほどのdateの部分を直しました。

<img width="831" alt="スクリーンショット 2022-11-19 21 24 25" src="https://user-images.githubusercontent.com/101074621/202850926-08bf814b-540a-4990-aaf7-7bf2743231c1.png">

2022-11-19 12:40 UTC, murata0705 commented
なるほど、weathers テーブルに api で取得したデータをそのままいれて、weather_forecasts にパースしたデータを入れるということですかね？

ちなみに書いていて気づきましたが、

1. 天気予報を下記を使って取得
  - city
  - date
2. アドバイスをかきを使って作成
  - weather_forecast
  - hair

という関係ですかね？もしかして。

1. city + date -> weather_forecast
2. weather_forecast + hair -> advice

2022-11-19 12:42 UTC, yuri315 commented
> なるほど、weathers テーブルに api で取得したデータをそのままいれて、weather_forecasts にパースしたデータを入れるということですかね？

その通りです。

> city + date -> weather_forecast
> weather_forecast + hair -> advice

その通りです。

2022-11-19 13:05 UTC, murata0705 commented
そしたら、十分に試行錯誤しましたし、レビューが長くなっていて担当も入れ替わっているので、このあたりで具体的にアドバイスしますね。

まずは必要なデータをグルーピングすると情報が整理しやすいです。エンティティ抽出といったりします。

今回は、

- ユーザー
- 天気予報
- ヘアーアドバイス
- アドバイスをもらうにあたっての要望
  - 場所
  - 時間
- アドバイスするにあたって必要な情報
  - 髪質等

に分けるとスッキリしそうです。

具体的には下記みたいな感じで作り直してみましょう。（急いで書いたので英語がちょっと正しいかあれですが。。）

- ユーザー（ users ）
  - fk 以外全部
- 天気予報（ weather_forecasts ）
  - user_id
  - weather_forecasts テーブルのカラムすべて
  - data ( api で取得したデータ。wether_result )
- ヘアーアドバイス（ hair_advices ）
  - user_id
  - advice
- アドバイスするにあたっての確認事項、要望（ advice_materials ）
  - user_id
  - city
  - forecast_day
- 髪質（ hair_features ）
  - user_id
  - hair_type

2022-11-19 13:09 UTC, murata0705 commented
こちら僕が最後まで見るので、僕にメンションしてもらって大丈夫です。

2022-11-19 13:41 UTC, yuri315 commented
ありがとうございます。

アドバイス頂いた内容で作成しました。
よろしくお願いいたします。
<img width="641" alt="スクリーンショット 2022-11-19 22 39 22" src="https://user-images.githubusercontent.com/101074621/202853555-21c07a8d-1be4-4f18-96a2-12251720aef7.png">

2022-11-20 03:45 UTC, murata0705 commented
良さそうです。リレーションの向きがすべて反対なので、修正しましょうか。

2022-11-20 14:50 UTC, yuri315 commented
リレーションの向き訂正しました。

よろしくお願いいたします。
<img width="647" alt="スクリーンショット 2022-11-20 23 48 39" src="https://user-images.githubusercontent.com/101074621/202908951-d66b26d4-8b3b-444d-8d62-27a6309f4078.png">

2022-11-21 02:58 UTC, murata0705 commented
👍🏻 です！
マージして実装にすすみましょう。

2022-11-22 03:25 UTC, yuri315 commented
ありがとうございます。

2022-11-22 03:30 UTC, merged